apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: realworld-front-angular-prod
patches:
- target:
    kind: Namespace
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: realworld-front-angular-prod
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
- service.yaml
